prevent database output being written to the file

diff --git a/bin/sync-db b/bin/sync-db
--- a/bin/sync-db
+++ b/bin/sync-db
@@ -119,7 +119,7 @@ then
 
 
     echo "*** Connecting to $ORIGIN_ENV_NAME Server"
-    ssh $ORIGIN_SSH_OPTIONS $ORIGIN_REMOTE_SSH "mkdir -p $ORIGIN_PROJECT_DIR/$DBDUMPS_DIR && [[ -f $ORIGIN_PROJECT_DIR/$DBDUMPS_DIR/$FILENAME ]] && echo \"    - Skipping export because a dump already exists for today\" && exit ||  echo \"    - Exporting database to dump file on server\" && mysqldump -u $ORIGIN_MYSQL_USER --password=\"$ORIGIN_ENV_DB_PASS\" $MYSQLDUMP_PARAMS $ORIGIN_MYSQL_DB_NAME > $ORIGIN_PROJECT_DIR/$DBDUMPS_DIR/tmp 2>&1 && mv $ORIGIN_PROJECT_DIR/$DBDUMPS_DIR/tmp $ORIGIN_PROJECT_DIR/$DBDUMPS_DIR/$FILENAME || { echo \"Could not export database, password may have been incorrect\"; exit 1; }"
+    ssh $ORIGIN_SSH_OPTIONS $ORIGIN_REMOTE_SSH "mkdir -p $ORIGIN_PROJECT_DIR/$DBDUMPS_DIR && [[ -f $ORIGIN_PROJECT_DIR/$DBDUMPS_DIR/$FILENAME ]] && echo \"    - Skipping export because a dump already exists for today\" && exit ||  echo \"    - Exporting database to dump file on server\" && mysqldump -u $ORIGIN_MYSQL_USER --password=\"$ORIGIN_ENV_DB_PASS\" $MYSQLDUMP_PARAMS $ORIGIN_MYSQL_DB_NAME > $ORIGIN_PROJECT_DIR/$DBDUMPS_DIR/tmp && mv $ORIGIN_PROJECT_DIR/$DBDUMPS_DIR/tmp $ORIGIN_PROJECT_DIR/$DBDUMPS_DIR/$FILENAME || { echo \"Could not export database, password may have been incorrect\"; exit 1; }"
     # copy file to server
 
     if [ -f  $LOCAL_DBDUMPS_DIR/$FILENAME ]
@@ -158,7 +158,7 @@ else
        fi
 
        echo "    - Exporting local database to dump file"
-       mysqldump -u $ORIGIN_MYSQL_USER --password="$ORIGIN_ENV_DB_PASS" "$MYSQLDUMP_PARAMS" $ORIGIN_MYSQL_DB_NAME > $LOCAL_DBDUMPS_DIR/tmp 2>&1 && mv $LOCAL_DBDUMPS_DIR/tmp $LOCAL_DBDUMPS_DIR/$FILENAME || { echo "Could not export database, password may have been incorrect"; exit 1; }
+       mysqldump -u $ORIGIN_MYSQL_USER --password="$ORIGIN_ENV_DB_PASS" "$MYSQLDUMP_PARAMS" $ORIGIN_MYSQL_DB_NAME > $LOCAL_DBDUMPS_DIR/tmp  && mv $LOCAL_DBDUMPS_DIR/tmp $LOCAL_DBDUMPS_DIR/$FILENAME || { echo "Could not export database, password may have been incorrect"; exit 1; }
 
        # copy file to server
        echo "    - Copying local database dump file to $DESTINATION_ENV_NAME server"
@@ -177,7 +177,7 @@ else
     then
 
         echo "*** Connecting to $ORIGIN_ENV_NAME Server"
-        ssh $ORIGIN_SSH_OPTIONS $ORIGIN_REMOTE_SSH "mkdir -p $ORIGIN_PROJECT_DIR/$DBDUMPS_DIR && [[ -f $ORIGIN_PROJECT_DIR/$DBDUMPS_DIR/$FILENAME ]] && echo \"    - Skipping export because a dump already exists for today\" && exit || echo \"    - Exporting database to dump file on server\" && mysqldump -u $ORIGIN_MYSQL_USER --password=\"$ORIGIN_ENV_DB_PASS\" $MYSQLDUMP_PARAMS $ORIGIN_MYSQL_DB_NAME > $ORIGIN_PROJECT_DIR/$DBDUMPS_DIR/tmp 2>&1 && mv $ORIGIN_PROJECT_DIR/$DBDUMPS_DIR/tmp $ORIGIN_PROJECT_DIR/$DBDUMPS_DIR/$FILENAME || { echo \"Could not export database, password may have been incorrect\"; exit 1; }"
+        ssh $ORIGIN_SSH_OPTIONS $ORIGIN_REMOTE_SSH "mkdir -p $ORIGIN_PROJECT_DIR/$DBDUMPS_DIR && [[ -f $ORIGIN_PROJECT_DIR/$DBDUMPS_DIR/$FILENAME ]] && echo \"    - Skipping export because a dump already exists for today\" && exit || echo \"    - Exporting database to dump file on server\" && mysqldump -u $ORIGIN_MYSQL_USER --password=\"$ORIGIN_ENV_DB_PASS\" $MYSQLDUMP_PARAMS $ORIGIN_MYSQL_DB_NAME > $ORIGIN_PROJECT_DIR/$DBDUMPS_DIR/tmp && mv $ORIGIN_PROJECT_DIR/$DBDUMPS_DIR/tmp $ORIGIN_PROJECT_DIR/$DBDUMPS_DIR/$FILENAME || { echo \"Could not export database, password may have been incorrect\"; exit 1; }"
         # copy file to server
 
         if [ -f  $LOCAL_DBDUMPS_DIR/$FILENAME ]
