allow database sync from server A to server B using the local machine as a proxy

diff --git a/bin/sync-db b/bin/sync-db
--- a/bin/sync-db
+++ b/bin/sync-db
@@ -111,48 +111,31 @@ FILENAME=$DATE'-'$ORIGIN_ENV_NAME'.sql'
 if [ "$ORIGIN_ENV_NAME" != "local" ] && [ "$DESTINATION_ENV_NAME" != "local" ]
 then
 
-    if [ "$DESTINATION_ENV_NAME" = "vagrant" ]
+
+    echo "*** Connecting to $ORIGIN_ENV_NAME Server"
+    ssh $ORIGIN_SSH_OPTIONS $ORIGIN_REMOTE_SSH "mkdir -p $ORIGIN_REMOTE_ROOT/$DBDUMPS_DIR && [[ -f $ORIGIN_REMOTE_ROOT/$DBDUMPS_DIR/$FILENAME ]] && echo \"    - Skipping export because a dump already exists for today\" && exit ||  echo \"    - Exporting database to dump file on server\" && mysqldump -u $ORIGIN_MYSQL_USER --password=\"$ORIGIN_ENV_DB_PASS\" \"$MYSQLDUMP_PARAMS\" $ORIGIN_MYSQL_DB_NAME > $ORIGIN_REMOTE_ROOT/$DBDUMPS_DIR/tmp 2>&1 && mv $ORIGIN_REMOTE_ROOT/$DBDUMPS_DIR/tmp $ORIGIN_REMOTE_ROOT/$DBDUMPS_DIR/$FILENAME || { echo \"Could not export database, password may have been incorrect\"; exit 1; }"
+    # copy file to server
+
+    if [ -f  $LOCAL_DBDUMPS_DIR/$FILENAME ]
     then
+        echo "    - Removing local database dump file"
+        rm $LOCAL_DBDUMPS_DIR/$FILENAME
+    fi
 
-        echo "*** Connecting to $ORIGIN_ENV_NAME Server"
-        ssh $ORIGIN_SSH_OPTIONS $ORIGIN_REMOTE_SSH "mkdir -p $ORIGIN_REMOTE_ROOT/$DBDUMPS_DIR && [[ -f $ORIGIN_REMOTE_ROOT/$DBDUMPS_DIR/$FILENAME ]] && echo \"    - Skipping export because a dump already exists for today\" && exit ||  echo \"    - Exporting database to dump file on server\" && mysqldump -u $ORIGIN_MYSQL_USER --password=\"$ORIGIN_ENV_DB_PASS\" \"$MYSQLDUMP_PARAMS\" $ORIGIN_MYSQL_DB_NAME > $ORIGIN_REMOTE_ROOT/$DBDUMPS_DIR/tmp 2>&1 && mv $ORIGIN_REMOTE_ROOT/$DBDUMPS_DIR/tmp $ORIGIN_REMOTE_ROOT/$DBDUMPS_DIR/$FILENAME || { echo \"Could not export database, password may have been incorrect\"; exit 1; }"
-        # copy file to server
+    echo "    - Copying $ORIGIN_ENV_NAME database dump file to local repository"
+    scp -Cr $ORIGIN_SCP_OPTIONS $ORIGIN_REMOTE_SSH:$ORIGIN_REMOTE_ROOT/$DBDUMPS_DIR/$FILENAME $LOCAL_DBDUMPS_DIR/$FILENAME
 
-        if [ -f  $LOCAL_DBDUMPS_DIR/$FILENAME ]
-        then
-            echo "    - Removing local database dump file"
-            rm $LOCAL_DBDUMPS_DIR/$FILENAME
-        fi
+    ssh $DESTINATION_SSH_OPTIONS $DESTINATION_REMOTE_SSH "mkdir -p $DESTINATION_REMOTE_ROOT/$DBDUMPS_DIR"
 
-        echo "    - Copying $ORIGIN_ENV_NAME database dump file to local repository"
-        scp -Cr $ORIGIN_SCP_OPTIONS $ORIGIN_REMOTE_SSH:$ORIGIN_REMOTE_ROOT/$DBDUMPS_DIR/$FILENAME $LOCAL_DBDUMPS_DIR/$FILENAME
+    echo "    - Copying local database dump file to $DESTINATION_ENV_NAME server"
+    scp -Cr $DESTINATION_SCP_OPTIONS $LOCAL_DBDUMPS_DIR/$FILENAME $DESTINATION_REMOTE_SSH:$DESTINATION_REMOTE_ROOT/$DBDUMPS_DIR/$FILENAME
+    # import
 
-        ssh $DESTINATION_SSH_OPTIONS $DESTINATION_REMOTE_SSH "mkdir -p $DESTINATION_REMOTE_ROOT/$DBDUMPS_DIR"
-
-        echo "    - Copying local database dump file to $DESTINATION_ENV_NAME server"
-        scp -Cr $DESTINATION_SCP_OPTIONS $LOCAL_DBDUMPS_DIR/$FILENAME $DESTINATION_REMOTE_SSH:$DESTINATION_REMOTE_ROOT/$DBDUMPS_DIR/$FILENAME
-        # import
-
-        if [ ! "$OPTIONS" = "--backup" ] && [ ! "$OPTIONS" = "-b" ]
-        then
-           echo "    - Importing database on $DESTINATION_ENV_NAME Server"
-           ssh $DESTINATION_SSH_OPTIONS $DESTINATION_REMOTE_SSH "mysql -u $DESTINATION_MYSQL_USER --password=$DESTINATION_ENV_DB_PASS $DESTINATION_MYSQL_DB_NAME < $DESTINATION_REMOTE_ROOT/$DBDUMPS_DIR/$FILENAME && echo \"    - Updating setting values in the database to environment specific values\" && echo \"$POST_IMPORT_DB_COMMAND\" | mysql -u $DESTINATION_MYSQL_USER --password=\"$DESTINATION_ENV_DB_PASS\" $DESTINATION_MYSQL_DB_NAME"
-        fi
-
-    else
-
-
-        echo "*** Connecting to $ORIGIN_ENV_NAME Server"
-        # ssh in, make directory if needed and dump database
-
-         ssh $ORIGIN_SSH_OPTIONS $ORIGIN_REMOTE_SSH "mkdir -p $ORIGIN_REMOTE_ROOT/$DBDUMPS_DIR && echo \"    - Exporting database to dump file on server\" && mysqldump -u $ORIGIN_MYSQL_USER --password=\"$ORIGIN_ENV_DB_PASS\" \"$MYSQLDUMP_PARAMS\" $ORIGIN_MYSQL_DB_NAME > $ORIGIN_REMOTE_ROOT/$DBDUMPS_DIR/tmp 2>&1 && mv $ORIGIN_REMOTE_ROOT/$DBDUMPS_DIR/tmp $ORIGIN_REMOTE_ROOT/$DBDUMPS_DIR/$FILENAME || { echo \"Could not export database, password may have been incorrect\"; exit 1; }"
-
-        echo "*** Connecting to $DESTINATION_ENV_NAME Server"
-
-        # ssh in, make directory if needed and scp database across from the other and then import
-         ssh $DESTINATION_SSH_OPTIONS $DESTINATION_REMOTE_SSH "mkdir -p $DESTINATION_REMOTE_ROOT/$DBDUMPS_DIR && echo \"    - Copying database dump file from $ORIGIN_ENV_NAME server\" && scp -Cr ${ORIGIN_SCP_OPTIONS} $ORIGIN_REMOTE_SSH:$ORIGIN_REMOTE_ROOT/$DBDUMPS_DIR/$FILENAME $DESTINATION_REMOTE_ROOT/$DBDUMPS_DIR/$FILENAME && [ ! \"$OPTIONS\" = \"--backup\" ] && [ ! \"$OPTIONS\" = \"-b\" ] && echo \"    - Importing database on $DESTINATION_ENV_NAME Server\" && mysql -u $DESTINATION_MYSQL_USER --password=\"$DESTINATION_ENV_DB_PASS\" $DESTINATION_MYSQL_DB_NAME < $DBDUMPS_DIR/$FILENAME && echo \"    - Updating setting values in the database to environment specific values\" && echo \"$POST_IMPORT_DB_COMMAND\" | mysql -u $DESTINATION_MYSQL_USER --password=\"$DESTINATION_ENV_DB_PASS\" $DESTINATION_MYSQL_DB_NAME"
-
-     fi
+    if [ ! "$OPTIONS" = "--backup" ] && [ ! "$OPTIONS" = "-b" ]
+    then
+       echo "    - Importing database on $DESTINATION_ENV_NAME Server"
+       ssh $DESTINATION_SSH_OPTIONS $DESTINATION_REMOTE_SSH "mysql -u $DESTINATION_MYSQL_USER --password=$DESTINATION_ENV_DB_PASS $DESTINATION_MYSQL_DB_NAME < $DESTINATION_REMOTE_ROOT/$DBDUMPS_DIR/$FILENAME && echo \"    - Updating setting values in the database to environment specific values\" && echo \"$POST_IMPORT_DB_COMMAND\" | mysql -u $DESTINATION_MYSQL_USER --password=\"$DESTINATION_ENV_DB_PASS\" $DESTINATION_MYSQL_DB_NAME"
+    fi
 
 else
 
